jsonld-java/jsonld-java

core/src/main/java/com/github/jsonldjava/utils/JsonUtils.java, core/src/test/java/com/github/jsonldjava/utils/JsonUtilsTest.java, integration/sesame/src/test/java/com/github/jsonldjava/sesame/SesameLocaleNumericTest.java
This is a potential fix for issue #144.
A decision to be made is whether this invalidation of existing (but wrong) data is what the community wants.  (See, for example, the fix to the sesame integration testing which illustrates this)
One consideration for this fix is that no RDF is generated because of trailing content.  It would be better if RDF was generated then a parse error thrown. This does not seem is not possible without changing the way parsing happens, and the API, because the JsonParser goes out of scope at the end of JSON parsing, before production of RDF.
=> Fix for issue #144.

core/src/main/java/com/github/jsonldjava/core/Context.java, core/src/test/java/com/github/jsonldjava/core/LongestPrefixTest.java, core/src/test/resources/custom/contexttest-0003.jsonld
Add regression test to verify the behaviour for issue #153 , where the spec checks for the shortest shortened URI (and then does a lexicographical comparison), and does not check for the longest prefix before shortening the URI.
=> GitHub 153

core/src/main/java/com/github/jsonldjava/core/DocumentLoader.java, core/src/test/java/com/github/jsonldjava/core/DocumentLoaderTest.java
It is hard to come up with a testcase for #160 because I don't know how to test for hanging. Nevertheless, this patch fixes #160 by closing the response (https://github.com/jsonld-java/jsonld-java/compare/master...kaefer3000:master#diff-eb9bf0691266ec47924e78c27645604bR122). To close the response, I had to make sure that the HTTPresponses are closeable. To achieve that, also the responses from the cache had to be closeable. To get there, I had to update the code to the latest http client api. Yet, now the JarCache does not work any more (see https://github.com/jsonld-java/jsonld-java/compare/master...kaefer3000:master#diff-eb9bf0691266ec47924e78c27645604bR150 . By re-enabling it, a test case fails).
=> fixes #160 updating some http client code to latest api

core/src/main/java/com/github/jsonldjava/core/DocumentLoader.java, core/src/main/java/com/github/jsonldjava/utils/JsonUtils.java, core/src/test/java/com/github/jsonldjava/core/ArrayContextToRDFTest.java, core/src/test/java/com/github/jsonldjava/core/LongestPrefixTest.java
There are many DocumentLoader implementations that would fit better as static methods in JSONUtils for maintenance purposes. The DocumentLoader methods have been deprecated for future removal
=> Migrate DocumentLoader static implementations to JSONUtils

core/src/main/java/com/github/jsonldjava/core/Context.java, core/src/main/java/com/github/jsonldjava/core/JsonLdApi.java, core/src/main/java/com/github/jsonldjava/core/JsonLdConsts.java, core/src/main/java/com/github/jsonldjava/core/JsonLdProcessor.java, core/src/test/java/com/github/jsonldjava/core/LocalBaseTest.java, core/src/test/resources/custom/base-0001-in.jsonld, core/src/test/resources/custom/base-0001-out.jsonld, core/src/test/resources/custom/base-0002-in.jsonld, core/src/test/resources/custom/base-0002-out.jsonld
The JSONLD-API Context Processing Algorithm is specified as a recursive algorithm, but it doesn't seem to take into account that remote contexts must be operated on differently to the local context when they are mixed together. In particular, remote contexts must not propagate @base declarations out to the final context, although almost all of the rest of the context is propagated out otherwise.
This issue adds two regression tests, one with local context first, and the other with remote context first that demonstrate the issue. The regression test with local context first worked before the fix, but the remote context first was corrupting the final context by propagating an empty @base declaration out for some reason.
Fix for the issue is to introduce an inner private recursion method and …
=> Fix issue #175 using a hack for recursive context processing

.travis.yml, README.md, core/src/main/java/com/github/jsonldjava/core/JsonLdApi.java, core/src/main/java/com/github/jsonldjava/core/JsonLdUtils.java, core/src/main/java/com/github/jsonldjava/utils/Obj.java, core/src/test/java/com/github/jsonldjava/core/JsonLdPerformanceTest.java, pom.xml
Adds some performance tests, mostly related to issue #172 and pull request #173 that verify the existing method has performance dropoffs in some cases where the datasets are very uniform in terms of subject/predicate with many objects.
Also adds another "deprecated/experimental" method that could be called by users who know that they are feeding deduplicated RDFDataset objects into JSONLD-Java. Opened a new issue for deduplicating RDFDataset objects, issue #177 to follow up after this is merged.
=> Add performance tests for toRDF and expand and pretty printing

core/src/test/java/com/github/jsonldjava/core/DocumentLoaderTest.java
Doesn't seem to be an issue locally with jsonld-java, so disabling the
regression tests.
=> issue#180 : Add disabled regression tests for schema.org

core/src/main/java/com/github/jsonldjava/core/JsonLdApi.java, core/src/main/java/com/github/jsonldjava/core/JsonLdOptions.java, core/src/main/java/com/github/jsonldjava/core/JsonLdProcessor.java, core/src/test/java/com/github/jsonldjava/core/JsonLdFramingTest.java, core/src/test/resources/custom/frame-0002-frame.jsonld, core/src/test/resources/custom/frame-0002-in.jsonld, core/src/test/resources/custom/frame-0002-out.jsonld
The array compaction preference setup on JsonLdOptions and passed to the frame method was not being passed through to the compaction algorithm that is run as part of the framing algorithm.
Fixes issue #182
=> Issue #182 framing compaction of arrays

core/src/main/java/com/github/jsonldjava/core/RDFDataset.java, core/src/test/java/com/github/jsonldjava/core/NodeCompareTest.java, core/src/test/java/com/github/jsonldjava/core/QuadCompareTest.java
The Node.compareTo() of `RDFDataset.Literal` was broken in that it didn't compare the `.getValue()`, also it didn't compare `.getLanguage()` or `.getDataType()`, assuming they were equal as long as both were null.
This broke Commons RDF which assumed Nodes could be compared for their value, which was only true for `IRI` and `BlankNode`.
This PR adds unit tests for almost all the possible `Node` comparisons as well as fixing the problem in `Literal.compareTo()`.
I am not certain about keeping the datatype null-checks - as it means for instance a Literal with explicit XSD_STRING differs from one without. Also not sure if literals with language tags should even compare data types at all.
=> Literal compare was broken

README.md, core/src/main/java/com/github/jsonldjava/core/DocumentLoader.java, core/src/main/java/com/github/jsonldjava/core/JsonLdError.java, core/src/test/java/com/github/jsonldjava/core/DocumentLoaderTest.java
I added the ability to load context files from strings instead of through the "jarcache.json" function, as that depends upon files being available through "file://" URIs on the classpath (bad presumption). This also gets around the problem of conflicting "jarcache.json" instances when building reusable libraries.
=> Added injected string-based context

core/src/main/java/com/github/jsonldjava/core/JsonLdApi.java, core/src/main/java/com/github/jsonldjava/core/JsonLdConsts.java, core/src/main/java/com/github/jsonldjava/core/JsonLdError.java, core/src/main/java/com/github/jsonldjava/core/JsonLdOptions.java, core/src/main/java/com/github/jsonldjava/core/JsonLdProcessor.java, core/src/test/resources/json-ld.org/frame-0030-frame.jsonld, core/src/test/resources/json-ld.org/frame-0030-in.jsonld, core/src/test/resources/json-ld.org/frame-0030-out.jsonld, core/src/test/resources/json-ld.org/frame-manifest.jsonld
- support new `@embed` values (backward compatible), avoid circular embedding
- support framing by `@id`
- fix a bug with `pruneBlankNodes` when a blank node was present 3 times
- comment the framing algorithm code
=> Framing fixes

core/src/main/java/com/github/jsonldjava/core/JsonLdOptions.java, core/src/test/java/com/github/jsonldjava/core/JsonLdFramingTest.java, core/src/test/resources/custom/frame-0008-frame.jsonld, core/src/test/resources/custom/frame-0008-in.jsonld, core/src/test/resources/custom/frame-0008-out.jsonld
Provides a test for frames using `@embed:@always`.
This complements 4fe56fd and shows that #150
is indeed resolved.
Also fixes a "switch" fallthrough bug in JsonLdOptions.
=> 150 add test for embedding same data multiple times

README.md, core/src/main/java/com/github/jsonldjava/utils/JsonUtils.java
Ensure CloseableHttpResponse is closed before leaving ``JsonUtils.fromURL``. In successful cases, it was possibly being autoclosed when the stream was exhausted. This change ensures that it is explicitly closed in all cases.
=> Fix #222 : Ensure CloseableHttpResponse is closed in fromURL

core/pom.xml
The Guava shading in v0.12 works great in an ordinary class loading context, but I have had trouble with OSGi. For example, the `jsonld-java` bundle's OSGi metadata contains:
```
[IMPEXP]
Import-Package
...
com.google.common.cache                {version=[24.1,25)}
com.google.common.collect              {version=[24.1,25)}
```
And so, in order to provision v0.12 in Karaf, I need to also install Guava 24.1. But given the shading that is already done on the Guava classes (and the inclusion of those classes in the `jsonld-java` jar, it should not be necessary to depend on an external Guava bundle.
It appears that the `maven-bundle-plugin` doesn't take the relocation of these packages into consideration when it generates the list of import dependencies. The change in this PR explicitly …
=> Exclude Guava imports in OSGi metadata

core/src/main/java/com/github/jsonldjava/core/JsonLdApi.java, core/src/test/java/com/github/jsonldjava/core/JsonLdFramingTest.java, core/src/test/resources/custom/frame-0010-frame.jsonld, core/src/test/resources/custom/frame-0010-out.jsonld, core/src/test/resources/json-ld.org/fromRdf-0020-in.nq, core/src/test/resources/json-ld.org/fromRdf-0020-out.jsonld, core/src/test/resources/json-ld.org/fromRdf-manifest.jsonld
Fixes #242
As described on the issue, from the following triples
```
<http://example.com/Subj1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.com/Type> .
<http://example.com/Type> <http://www.w3.org/1999/02/22-rdf-syntax-ns#label> "myLabel" .
```
the following json should be created (event when useRdfType = false):
```json
{
"@id": "http://example.com/Subj1",
"http://www.w3.org/1999/02/22-rdf-syntax-ns#type": {
"http://www.w3.org/1999/02/22-rdf-syntax-ns#label": "myLabel"
}
}
```
=> Added fix for wrong rdf:type to @type conversion

core/src/main/java/com/github/jsonldjava/core/Context.java, core/src/test/java/com/github/jsonldjava/core/ContextTest.java
I think with this we can resolve #141.
The actual issue of producing invalid output from Jena has been fixed in Jena as described by @afs in https://github.com/jsonld-java/jsonld-java/issues/141#issuecomment-99384246. This pull request adds throwing an error as mentioned by @ansell in https://github.com/jsonld-java/jsonld-java/issues/141#issuecomment-99252669.
=> Throw error on empty key in context

pom.xml
Please update to Jackson v2.9.8.
(In response to dependency security scans.)
=> Upgrade to Jackson 2.9.8

pom.xml
Response to CVE-2019-12086 (which does not appear to impact this project).
But better to update to help downstream users who apply security scanners.
=> Update jackson to v2.9.9

pom.xml
This upgrade is for CVE-2019-12814.
=> Update version of jackson-databind to 2.9.9.1

pom.xml
More security issues - recommendation is now version 2.9.9.2.
=> Update version of jackson-databind to 2.9.9.2

pom.xml
Update to 2.9.10 as now recommended:
Since 2.9.9.2, there have been:
Jackson 2.9.10 covers:
CVE-2019-14540
CVE-2019-16335
Jackson 2.9.9.3 addressed:
CVE-2019-14379
Because the versions of jackson-core and jackson-databind now align, remove the databind specific setting.
=> Update version of jackson.core to 2.9.10

pom.xml
This PR updates Jackson to 2.10.0 from 2.9.10. It passes "mvn verify".
2.10.x has a more secure "databind" component that should bring to the end the stream of 2.9.x updates for CVEs.
Background for the design change for the security:
https://blog.sonatype.com/jackson-databind-the-end-of-the-blacklist
Jackson 2.10 features - 2.x API backwards compatibility is a goal:
https://medium.com/@cowtowncoder/jackson-2-10-features-cd880674d8a2
Explanation of the databind vulnerability:
https://medium.com/@cowtowncoder/on-jackson-cves-dont-panic-here-is-what-you-need-to-know-54cd0d6e8062
=> Update to Jackson 2.10.0

core/pom.xml
This library is needed by Guava internally, so it should also be shaded alongside Guava itself.
=> Shade Guava's internal failureaccess dependency.

core/pom.xml
This fixes an issue where google have bundled some guava code into a different top level package to the rest of guava.
Fixes #293 
Signed-off-by: Peter Ansell <p_ansell@yahoo.com>
=> issue #293 : Add com.google.thirdparty to shading

core/src/main/java/com/github/jsonldjava/core/Context.java, core/src/main/java/com/github/jsonldjava/core/JsonLdProcessor.java, core/src/test/java/com/github/jsonldjava/core/ContextCompactionTest.java, core/src/test/java/com/github/jsonldjava/core/ContextFlatteningTest.java, core/src/test/java/com/github/jsonldjava/core/ContextFramingTest.java, core/src/test/java/com/github/jsonldjava/core/ContextSerializationTest.java, core/src/test/resources/custom/contexttest-0005.jsonld
Fixes https://github.com/jsonld-java/jsonld-java/issues/295
Fixes https://github.com/jsonld-java/jsonld-java/issues/184
Fixes https://github.com/jsonld-java/jsonld-java/issues/297
Fixes https://github.com/jsonld-java/jsonld-java/issues/298
=> Fixed returned @context issues when the context is a remote context

core/src/main/java/com/github/jsonldjava/core/Context.java, core/src/test/java/com/github/jsonldjava/core/ContextRecursionTest.java
Fixes https://github.com/jsonld-java/jsonld-java/issues/302
The problem was with the fact that the list of visited remoteContexts was mutated while recursing.
=> Throw RECURSIVE_CONTEXT_INCLUSION only when cyclic dependency exists

core/src/main/java/com/github/jsonldjava/core/Context.java, core/src/test/java/com/github/jsonldjava/core/DocumentLoaderTest.java
If the remote context is not relative and seems to be a http URI
don't prefix the base IRI to it.
The remote context is not validated nor tested if it's resolvable.
It's just tested if it's not a relative URI - which is totally possible
and would, in conjunction with a base IRI, made into valid remote
context.
See #304.
=> Ignore @base if remote context is not relative

core/src/main/java/com/github/jsonldjava/core/JsonLdApi.java, core/src/test/java/com/github/jsonldjava/core/JsonLdToRdfTest.java
Fixes https://github.com/jsonld-java/jsonld-java/issues/301
It seems that when [fixing a previous issue with rdfToJson (related to @type)](https://github.com/jsonld-java/jsonld-java/pull/245) I introduced this bug.
=> rdfToJson edge case when object = subject and predicate = rdf:type

core/pom.xml, core/src/test/resources/log4j.properties, pom.xml
Switch our tests to log using logback rather than log4j.
Avoiding possible issue with log4j due to https://nvd.nist.gov/vuln/detail/CVE-2021-44228 , even though it was only in the `test` scope and unlikely to be pushed to downstream without them explicitly choosing log4j as their slf4j logger implementation.
Signed-off-by: Peter Ansell <p_ansell@yahoo.com>
=> issue #322 : Switch test logging from log4j to logback
